In [1]:
import torch
import interface

C:\Users\Иван\AppData\Roaming\Python\Python312\site-packages\torch\utils\_pytree.py:185: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(


In [2]:
class MyModel(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def __call__(self, x):
        shape = [t for t in x.shape]
        shape[-2] = 5
        return torch.randn(shape)

In [3]:
seq = torch.randn((1234, 2))
model = MyModel()

In [4]:
inference = interface.ModelInterference({"mode": "model_variable", "model_variable": model})

In [5]:
inference.predict_single(seq)

tensor([[-0.3093, -0.5262]])

In [6]:
inference.predict_sequence(seq, 10)

tensor([[-1.0537, -0.5101],
        [ 0.6607,  0.2821],
        [-0.6440, -0.8932],
        [ 0.2533,  0.7604],
        [-0.9332, -1.0344],
        [ 0.3231, -0.7891],
        [-0.9250, -1.6772],
        [ 0.1480, -0.6139],
        [ 1.1894,  0.5161],
        [-0.4586,  1.2325]])

In [7]:
# раскомментить код при следующей ошибке и при условии, что код запущен на виндоус
# NotImplementedError: cannot instantiate 'PosixPath' on your system
import pathlib
temp = pathlib.PosixPath
pathlib.PosixPath = pathlib.WindowsPath

In [8]:
from tsai.inference import load_learner

real_model = interface.TSAIModel("model\patchTST.pt")
real_inference = interface.ModelInterference({"mode": "model_variable", "model_variable": real_model})

<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
C:\Users\Иван\AppData\Local\Temp\ipykernel_60932\3983595471.py:3: SyntaxWarning: invalid escape sequence '\p'
  real_model = interface.TSAIModel("model\patchTST.pt")
C:\Users\Иван\AppData\Roaming\Python\Python312\site-packages\fastai\learner.py:455: UserWarning: load_learner` uses Python's insecure pickle module, which can execute malicious arbitrary code when loading. Only load files you trust.
If you only need to load model weights and optimizer state, use the safe `Learner.load` instead.
  warn("load_learner` uses Python's insecure pickle module, which can execute malicious arbitrary code when loading. Only load files you trust.\nIf you only need to load model weights and optimizer state, use the safe `Learner.load` instead.")


In [9]:
seq = torch.randn((1, 500, 2))
real_inference.predict_single(seq), real_inference.predict_single(seq), real_inference.predict_single(seq)

(tensor([[[0.7024, 0.3472]]]),
 tensor([[[0.7024, 0.3472]]]),
 tensor([[[0.7024, 0.3472]]]))

In [10]:
real_inference.predict_sequence(seq, 10)

tensor([[[0.7024, 0.3472],
         [0.2677, 0.7157],
         [0.5007, 0.4572],
         [0.1938, 0.4410],
         [0.4080, 0.2923],
         [0.3843, 0.1316],
         [0.0129, 0.1558],
         [0.1077, 0.1738],
         [0.1440, 0.2450],
         [0.0200, 0.4497]]])

In [11]:
seq = seq[0]
seq.shape

torch.Size([500, 2])