In [1]:
import pandas as pd
import os

In [2]:
def correct_folder(nbr, folder, class_name, delimeter):
    rst = []
    for x in str(nbr).split(delimeter):
        if str(x) in os.listdir(os.path.join(folder, class_name)):
            rst.append(x)
        else:
            print(x)
            print(sorted(os.listdir(os.path.join(folder, class_name)), key=int))
    if len(rst):
        return delimeter.join(rst)
    return None

In [3]:
sick_info = pd.read_excel("itelma_dataset/hypoxia.xlsx")["folder_id"].iloc[1:].reset_index(drop=True)
sick_info = pd.DataFrame(data=sick_info, columns=["folder_id"])
sick_info["has_hypoxia"] = True
sick_info["folder_id"] = sick_info["folder_id"].apply(lambda x: correct_folder(x, "itelma_dataset", "hypoxia", ","))
sick_info = sick_info[sick_info["folder_id"].notna()]
sick_info

15
['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '13', '14', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '27', '28', '30', '31', '32', '50']
26
['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '13', '14', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '27', '28', '30', '31', '32', '50']


folder_id  has_hypoxia
0          2         True
1         13         True
2         22         True
3         16         True
4          3         True
5         10         True
6         21         True
7          7         True
8          5         True
9          1         True
10         8         True
11         4         True
12        17         True
13        18         True
14         6         True
15        14         True
17        20         True
18        19         True
19         9         True
20        14         True
21        30         True
22     31,32         True
23        50         True
24        23         True
25     24,25         True
26     27,28         True

In [4]:
fine_info = pd.read_excel("itelma_dataset/regular.xlsx", header=1)["Folder_id"].dropna().apply(lambda x: str(x).replace(";", ",")).reset_index(drop=True)
fine_info = pd.DataFrame(data=fine_info.to_numpy(), columns=["folder_id"])
fine_info["has_hypoxia"] = False
fine_info["folder_id"] = fine_info["folder_id"].apply(lambda x: correct_folder(x, "itelma_dataset", "regular", ","))
fine_info = fine_info[fine_info["folder_id"].notna()]
fine_info

48
['1', '2', '3', '5', '6', '7', '8', '9', '10', '11', '12', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '33', '34', '35', '36', '37', '38', '39', '40', '42', '43', '44', '45', '46', '51', '53', '54', '55', '56', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '114', '115', '117', '120', '121', '122', '123', '124', '125', '127', '128', '129', '130', '131', '132', '133', '134', '135', '136', '137', '138', '139', '140', '141', '142', '143', '144', '145', '146', '147', '148', '149', '150', '151', '152', '153', '154', '155', '156', '157', '158', '159', '160']
49
['1', '2', '3', '5', '6', '7', '8', '9', '10', '11', '12', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '33', '34', '35', '36', '37', '38', '39', '40', '42', '43', '44', '45', '46', '51', '53', '54', '55', '56', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '114', '115', '117', '120',

folder_id  has_hypoxia
0           155,156        False
1               150        False
2               139        False
3               134        False
4           128,129        False
5           114,115        False
6               112        False
7                 5        False
9                53        False
10              110        False
11          148,149        False
12      142,143,144        False
13          135,136        False
14              145        False
15            20,21        False
16          132,133        False
17          152,153        False
18         38,39,40        False
19          130,131        False
20          124,125        False
21              8,9        False
22          121,122        False
23              111        False
24  103,104,105,106        False
25            55,56        False
26                1        False
27              2,3        False
28              6,7        False
29               10        False
30            11,12        False
31               14        False
32               15        False
33         16,17,18        False
34               19        False
35      22,23,24,25        False
36            26,27        False
37            28,29        False
38               33        False
39               34        False
40            35,36        False
41               37        False
42               42        False
43            43,44        False
44               45        False
45               46        False
47               51        False
49               54        False
51  157,158,159,160        False
52              154        False
53              151        False
54              147        False
55              146        False
56          140,141        False
57          137,138        False
58              127        False
59              123        False
60              120        False
61              117        False
62          108,109        False
63              107        False

In [5]:
sick_info_val = sick_info[sick_info.index % 4 == 3]
sick_info_val

folder_id  has_hypoxia
3         16         True
7          7         True
11         4         True
15        14         True
19         9         True
23        50         True

In [6]:
sick_info_train = sick_info[sick_info.index % 4 != 3]
sick_info_train

folder_id  has_hypoxia
0          2         True
1         13         True
2         22         True
4          3         True
5         10         True
6         21         True
8          5         True
9          1         True
10         8         True
12        17         True
13        18         True
14         6         True
17        20         True
18        19         True
20        14         True
21        30         True
22     31,32         True
24        23         True
25     24,25         True
26     27,28         True

In [7]:
fine_info_val = fine_info[fine_info.index % 4 == 1]
fine_info_val

folder_id  has_hypoxia
1        150        False
5    114,115        False
9         53        False
13   135,136        False
17   152,153        False
21       8,9        False
25     55,56        False
29        10        False
33  16,17,18        False
37     28,29        False
41        37        False
45        46        False
49        54        False
53       151        False
57   137,138        False
61       117        False

In [8]:
fine_info_train = fine_info[fine_info.index % 4 != 1]
fine_info_train

folder_id  has_hypoxia
0           155,156        False
2               139        False
3               134        False
4           128,129        False
6               112        False
7                 5        False
10              110        False
11          148,149        False
12      142,143,144        False
14              145        False
15            20,21        False
16          132,133        False
18         38,39,40        False
19          130,131        False
20          124,125        False
22          121,122        False
23              111        False
24  103,104,105,106        False
26                1        False
27              2,3        False
28              6,7        False
30            11,12        False
31               14        False
32               15        False
34               19        False
35      22,23,24,25        False
36            26,27        False
38               33        False
39               34        False
40            35,36        False
42               42        False
43            43,44        False
44               45        False
47               51        False
51  157,158,159,160        False
52              154        False
54              147        False
55              146        False
56          140,141        False
58              127        False
59              123        False
60              120        False
62          108,109        False
63              107        False

In [9]:
info = pd.concat([sick_info_train, fine_info_train]).reset_index(drop=True).to_numpy()
info

array([['2', True],
       ['13', True],
       ['22', True],
       ['3', True],
       ['10', True],
       ['21', True],
       ['5', True],
       ['1', True],
       ['8', True],
       ['17', True],
       ['18', True],
       ['6', True],
       ['20', True],
       ['19', True],
       ['14', True],
       ['30', True],
       ['31,32', True],
       ['23', True],
       ['24,25', True],
       ['27,28', True],
       ['155,156', False],
       ['139', False],
       ['134', False],
       ['128,129', False],
       ['112', False],
       ['5', False],
       ['110', False],
       ['148,149', False],
       ['142,143,144', False],
       ['145', False],
       ['20,21', False],
       ['132,133', False],
       ['38,39,40', False],
       ['130,131', False],
       ['124,125', False],
       ['121,122', False],
       ['111', False],
       ['103,104,105,106', False],
       ['1', False],
       ['2,3', False],
       ['6,7', False],
       ['11,12', False],
       ['14', Fals

In [10]:
val_info = pd.concat([sick_info_val, fine_info_val]).reset_index(drop=True).to_numpy()
val_info

array([['16', True],
       ['7', True],
       ['4', True],
       ['14', True],
       ['9', True],
       ['50', True],
       ['150', False],
       ['114,115', False],
       ['53', False],
       ['135,136', False],
       ['152,153', False],
       ['8,9', False],
       ['55,56', False],
       ['10', False],
       ['16,17,18', False],
       ['28,29', False],
       ['37', False],
       ['46', False],
       ['54', False],
       ['151', False],
       ['137,138', False],
       ['117', False]], dtype=object)

In [11]:
import dataloader

In [12]:
ds = dataloader.HypoxiaDataset("./itelma_dataset", info)
ds_val = dataloader.HypoxiaDataset("./itelma_dataset", val_info)

In [13]:
ds[0]

({'bpm': tensor([174.7675, 174.7675, 174.7675,  ..., 168.3538, 168.3538, 168.3538]),
  'uterus': tensor([95.0032, 95.0032, 95.0032,  ..., 11.2265, 11.2265, 11.2265]),
  'bpm_ts': tensor([0.0000e+00, 1.2703e-01, 2.5406e-01,  ..., 8.1603e+02, 8.1616e+02,
          8.1629e+02]),
  'uterus_ts': tensor([0.0000e+00, 1.2703e-01, 2.5406e-01,  ..., 8.1591e+02, 8.1603e+02,
          8.1616e+02]),
  'folders': '2'},
 tensor([0., 1.]))

In [14]:
import torch
from torch import nn

In [15]:
dl = torch.utils.data.DataLoader(ds, batch_size=1, shuffle=True)
dl_val = torch.utils.data.DataLoader(ds_val, batch_size=1, shuffle=False)

In [16]:
import cnn, rnn_class, rnn_predict

In [17]:
'''layers = [32, 64, "max_pool", 64, "max_pool", 64, "max_pool", 128, "max_pool", 128, "max_pool"]
inp_deconv = 128
classes = 2
model = cnn.GlobalPoolingCNN("bpm", 1, inp_deconv, layers[:], classes)
#model_uterus = cnn.GlobalPoolingCNN("uterus", 1, inp_deconv, layers[:], classes)
#model = cnn.JoinEmbedClassifier(2, [model_bpm, model_uterus], [4, 8, 8, 16, 8, 8, 4], 2)'''

'layers = [32, 64, "max_pool", 64, "max_pool", 64, "max_pool", 128, "max_pool", 128, "max_pool"]\ninp_deconv = 128\nclasses = 2\nmodel = cnn.GlobalPoolingCNN("bpm", 1, inp_deconv, layers[:], classes)\n#model_uterus = cnn.GlobalPoolingCNN("uterus", 1, inp_deconv, layers[:], classes)\n#model = cnn.JoinEmbedClassifier(2, [model_bpm, model_uterus], [4, 8, 8, 16, 8, 8, 4], 2)'

In [18]:
emb_layers = [16, 32, 32, 32, 64, 64, 128]
emb_model = rnn_predict.TimeEmbed(1, 1, 2, emb_layers[:])
model = rnn_predict.GRUPredictor(8, 256, emb_model, emb_layers[-1] + 2, 1)

In [19]:
#rand_inp = torch.randn(8, 1, 128)
#model({"bpm": rand_inp, "uterus": rand_inp})

In [20]:
test_a = torch.randn(8, 2)
print(test_a)
print(torch.argmax(test_a, dim=0))
print(torch.argmax(test_a, dim=1))

tensor([[ 0.9680, -0.9120],
        [-0.2776,  0.8403],
        [-0.4001, -0.0806],
        [-0.4649,  0.0497],
        [ 1.4110, -0.0674],
        [ 1.3710, -0.3238],
        [-0.0623, -0.1140],
        [ 0.4450,  0.2769]])
tensor([4, 1])
tensor([0, 1, 1, 1, 0, 0, 0, 0])


In [21]:
EPOCHS = 50
device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)
#loss_fn = nn.CrossEntropyLoss(weight=torch.tensor([.75, 1.25], device=device))
loss_fn = nn.L1Loss()
optimizer = torch.optim.NAdam(model.parameters())
optimizer.zero_grad()

In [22]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

In [23]:
import warnings; warnings.filterwarnings("ignore")


for i in range(EPOCHS):
    model.train()
    loss_sum = 0
    sample_num = 0
    for _x_batch, y_batch in dl:
        #_x_batch = {k: v.to(device) for k, v in _x_batch.items()}
        #print(_x_batch["folders"], y_batch)
        y_batch = y_batch.to(device)
        x_batch_delta = torch.cat([torch.tensor([[0.0] for _ in range(len(y_batch))]), _x_batch["bpm_ts"][:, 1:] - _x_batch["bpm_ts"][:, :-1]], dim=1)
        t = int(torch.randint(100, 1000, (1,))[0])
        a = int(torch.randint(0, _x_batch["bpm"].shape[1] - t - 2, (1,))[0])
        x_batch = torch.stack([_x_batch["bpm"], _x_batch["bpm_ts"], x_batch_delta], dim=2)[..., a:a+t+2, :].contiguous().to(device)
        y_pred = model(x_batch[..., :-1, :])
        #print(y_batch.shape, y_pred.shape)
        loss = loss_fn(y_pred, x_batch[..., -1, :-2])
        loss.backward()
        loss_sum += loss.item()
        sample_num += len(y_batch)
        optimizer.step()
        optimizer.zero_grad()
    print(f"Avg loss on epoch {i + 1}/{EPOCHS} is {loss_sum / sample_num}")
    model.eval()
    loss_sum = 0
    sample_num = 0
    _y_pred = []
    _y_batch = []
    with torch.no_grad():
        for _x_batch, y_batch in dl_val:
            #_x_batch = {k: v.to(device) for k, v in _x_batch.items()}
            y_batch = y_batch.to(device)
            x_batch_delta = torch.cat([torch.tensor([[0.0] for _ in range(len(y_batch))]), _x_batch["bpm_ts"][:, 1:] - _x_batch["bpm_ts"][:, :-1]], dim=1)
            x_batch = torch.stack([_x_batch["bpm"], _x_batch["bpm_ts"], x_batch_delta], dim=2)[..., -501:, :].contiguous().to(device)
            y_pred = model(x_batch[..., :-1, :])
            #print(y_batch, y_pred)
            loss = loss_fn(y_pred, x_batch[..., -1, :-2])
            #loss.backward()
            loss_sum += loss.item()
            sample_num += len(y_batch)
            #optimizer.step()
            #optimizer.zero_grad()
            #_y_pred.extend(torch.argmax(y_pred, dim=1).tolist())
            #_y_batch.extend(torch.argmax(y_batch, dim=1).tolist())
    print(f"Avg loss on epoch {i + 1}/{EPOCHS} is {loss_sum / sample_num}")
    #print(f"Accuracy: {accuracy_score(_y_batch, _y_pred)}\nPrecision: {precision_score(_y_batch, _y_pred)}\nRecall: {recall_score(_y_batch, _y_pred)}\n")

Avg loss on epoch 1/50 is 114.76088297367096
Avg loss on epoch 1/50 is 105.18487722223455
Avg loss on epoch 2/50 is 84.91482698917389
Avg loss on epoch 2/50 is 74.0798071080988
Avg loss on epoch 3/50 is 53.103094935417175
Avg loss on epoch 3/50 is 47.33419262279164
Avg loss on epoch 4/50 is 22.005860686302185
Avg loss on epoch 4/50 is 32.01390075683594
Avg loss on epoch 5/50 is 37.78045701980591
Avg loss on epoch 5/50 is 185.52304909446022
Avg loss on epoch 6/50 is 179.60971355438232
Avg loss on epoch 6/50 is 166.6056768243963
Avg loss on epoch 7/50 is 96.3024582862854
Avg loss on epoch 7/50 is 31.053054809570312
Avg loss on epoch 8/50 is 13.68948757648468
Avg loss on epoch 8/50 is 30.103866577148438
Avg loss on epoch 9/50 is 13.677789807319641
Avg loss on epoch 9/50 is 30.056252219460227
Avg loss on epoch 10/50 is 14.381943702697754
Avg loss on epoch 10/50 is 31.043412642045453
Avg loss on epoch 11/50 is 15.422017216682434
Avg loss on epoch 11/50 is 30.245723377574574
Avg loss on epoc

In [24]:
_y_pred = []
_y_batch = []
'''with torch.no_grad():
    for x_batch, y_batch in dl_val:
        x_batch = {k: v.to(device) for k, v in x_batch.items()}
        y_batch = y_batch.to(device)
        y_pred = model(x_batch).detach()
        _y_pred.extend(torch.argmax(y_pred, dim=1).tolist())
        _y_batch.extend(torch.argmax(y_batch, dim=1).tolist())'''

'with torch.no_grad():\n    for x_batch, y_batch in dl_val:\n        x_batch = {k: v.to(device) for k, v in x_batch.items()}\n        y_batch = y_batch.to(device)\n        y_pred = model(x_batch).detach()\n        _y_pred.extend(torch.argmax(y_pred, dim=1).tolist())\n        _y_batch.extend(torch.argmax(y_batch, dim=1).tolist())'

In [25]:
print(_y_batch, sep=" ")
print(_y_pred, sep=" ")

[]
[]


In [26]:
accuracy_score(_y_batch, _y_pred)

nan